### ISSUE TITLE
maxPostSize for base64 images

### ISSUE THREAD

**Issue by Giosanu** [ip-b1-2017/fii-admission#2]
Transformarea imaginilor in base64 au necesitat o marire a maxPostSize. Acesta a fost facut doar pe serverul de la view-controller. Va trebui sa fie schimbat si la celelalte servere. 

**Step 1**

Adaugati acest cod in clasa unde se deschide serverul (Ex: in view-controller aceasta este FiiAdmisionApplication)

 

    @Bean
    EmbeddedServletContainerCustomizer containerCustomizer() throws Exception { 
    return (ConfigurableEmbeddedServletContainer container) -> {  
   
            if (container instanceof TomcatEmbeddedServletContainerFactory) {
   
                TomcatEmbeddedServletContainerFactory tomcat = (TomcatEmbeddedServletContainerFactory) container;
                tomcat.addConnectorCustomizers(
                        (connector) -> {
                           connector.setMaxPostSize(10000000);//10MB
                     }
                );
            }
        };
    } 

**Step 2** 

Se vor declansa niste erori, ALT-ENTER la sursa erorii ( " (connector)" ) -> alegeti optiunea "Set language level to 8: lambda.." etc.

**Step 3**

Adaugati 

`spring.http.multipart.max-file-size=12MB `
`spring.http.multipart.max-request-size=12MB`

in fisierul _application.properties_

**Comment by fenea** [comment]
ok, facem

**Comment by fenea** [comment]
Edi a facut, dar accept onorurile si eu.

**Comment by TED-996** [comment]
reopened cause it's not done

**Comment by fenea** [comment]
why?

**Comment by Giosanu** [comment]
because it's not, nu mai inchide issue fara sa intrebi/verifici. Thanks

**Comment by fenea** [comment]
am vorbit cu Edi atunci.
