### ISSUE TITLE
[MODEL] Salvat + verificat parola cum trebuie

### ISSUE THREAD

**Issue by TED-996** [ip-b1-2017/fii-admission#5]
Acum e plaintext, ceea ce e nasol.

Trebuie salvata ca SALTED HASH, SHA256 + salt de (minim) 16 caractere random.
Aveti exemplu + informatii aici (+ in multe alte locuri): https://en.wikipedia.org/wiki/Salt_(cryptography)#Example_usage

Thanks.

**Comment by MaximDragosAndrei** [comment]
Suntem pe calea cea buna.
Mai trebuie facuta testarea.
