### ISSUE TITLE
ResponseEntity<Integer> -> ResponseEntity<SuccessEntity>

### ISSUE THREAD

**Issue by AlexDomnaru** [ip-b1-2017/fii-admission#8]
Adresat catre integrare. In serverul de la model, acolo unde se returneaza ResponseEntity\<Integer\> ar fi mai ok sa se returneze ResponseEntity\<SuccessEntity\>. E mai clar, plus ca asta asteapta Controllerul de la Model.

**Comment by tavy14t** [comment]
ma ocup acum
