### ISSUE TITLE
[Model] Tabela Profesori + tabel sali

### ISSUE THREAD

**Issue by costeltuiu** [ip-b1-2017/fii-admission#9]
Scoateti va rog coloanele cu sali examen id si sali examen. Lasati doar nume, prenume si cnp. Iar la tabela sali lasati doar cod sala, etaj si nr locuri

**TABEL PROFI : NUME, PRENUME, CNP**
**TABEL SALI : ID, ETAJ, NR. LOCURI**

also puteti sa scoateti **SALI_EXAMEN** si **SALI_EXAMEN** candidat

**Comment by MaximDragosAndrei** [comment]
Solved.
I guess.

**Comment by tavy14t** [comment]
E rezolvat, s-au facut modificarile atat in db cat si in API-ul de back-end. Inca nu au fost scoase pachetele sali_examen si sali_examen_candidat din proiectul spring-boot, dar nu ne incurca...
